### ISSUE TITLE
Coveralls choked on re.compile pattern

### ISSUE THREAD

**Issue by pllim** [coveralls-clients/coveralls-python#175]
Travis CI log: https://travis-ci.org/spacetelescope/stsynphot_refactor/jobs/329655958

I had successfully run coveralls on this repo before and I have not modified the `re.compile` pattern in a long time. Hope someone could help. Thanks!

```
Traceback (most recent call last):
  File "/home/travis/miniconda/envs/test/lib/python3.6/site-packages/coverage/parser.py", line 363, in __init__
    self.code = compile_unicode(text, filename, "exec")
  File "/home/travis/miniconda/envs/test/lib/python3.6/site-packages/coverage/phystokens.py", line 286, in compile_unicode
    code = compile(source, filename, mode)
  File "/home/travis/build/spacetelescope/stsynphot_refactor/stsynphot/spectrum.py", line 34
    _interpfilepatt = re.compile('\[(?P<col>.*?)\]')  # pragma: no cover
                                ^
SyntaxError: invalid escape sequence \[
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/travis/miniconda/envs/test/lib/python3.6/site-packages/astropy/tests/helper.py", line 94, in _save_coverage
    cov.html_report(directory=os.path.join(rootdir, 'htmlcov'))
  File "/home/travis/miniconda/envs/test/lib/python3.6/site-packages/coverage/control.py", line 1090, in html_report
    return reporter.report(morfs)
  File "/home/travis/miniconda/envs/test/lib/python3.6/site-packages/coverage/html.py", line 139, in report
    self.report_files(self.html_file, morfs, self.config.html_dir)
  File "/home/travis/miniconda/envs/test/lib/python3.6/site-packages/coverage/report.py", line 91, in report_files
    report_fn(fr, self.coverage._analyze(fr))
  File "/home/travis/miniconda/envs/test/lib/python3.6/site-packages/coverage/control.py", line 963, in _analyze
    return Analysis(self.data, it)
  File "/home/travis/miniconda/envs/test/lib/python3.6/site-packages/coverage/results.py", line 19, in __init__
    self.statements = self.file_reporter.lines()
  File "/home/travis/miniconda/envs/test/lib/python3.6/site-packages/coverage/python.py", line 186, in lines
    return self.parser.statements
  File "/home/travis/miniconda/envs/test/lib/python3.6/site-packages/coverage/python.py", line 181, in parser
    self._parser.parse_source()
  File "/home/travis/miniconda/envs/test/lib/python3.6/site-packages/coverage/parser.py", line 237, in parse_source
    self._raw_parse()
  File "/home/travis/miniconda/envs/test/lib/python3.6/site-packages/coverage/parser.py", line 206, in _raw_parse
    self.raw_statements.update(self.byte_parser._find_statements())
  File "/home/travis/miniconda/envs/test/lib/python3.6/site-packages/coverage/parser.py", line 96, in byte_parser
    self._byte_parser = ByteParser(self.text, filename=self.filename)
  File "/home/travis/miniconda/envs/test/lib/python3.6/site-packages/coverage/parser.py", line 367, in __init__
    filename, synerr.msg, synerr.lineno
coverage.misc.NotPython: Couldn't parse '/home/travis/build/spacetelescope/stsynphot_refactor/stsynphot/spectrum.py' as Python source: 'invalid escape sequence \[' at line 34
```

**Comment by TheKevJames** [comment]
@pllim Hmm, looks like you are missing the [raw string](https://docs.python.org/3.6/library/re.html) identifier for your regexes -- ie. you should use `r'\[(?P<col>.*?)\]'` rather than simply `'(?P<col>.*?)\]'` (note the prefix `r`) in order to signal Python that you are looking for literal backslashes rather than escaping the next character.

You're likely seeing this issue since you bumped to Python 3.6, which IIRC has removed or deprecated the previous behavior of attempting to guess as to whether you meant to use a raw string.

Could you report back on whether switching to a raw string identifier fixes the issue?

**Comment by pllim** [comment]
Okay, it seems to work. Thank you!
