### ISSUE TITLE
Coveralls Breaks on urllib3 Dependency for python < 3

### ISSUE THREAD

**Issue by wwaltersp** [coveralls-clients/coveralls-python#189]
I believe that the issue is that coveralls lists [urllib3[secure]](https://github.com/coveralls-clients/coveralls-python/blob/eba54e4d19e40e3907e5fd516f68e8b4dc9e5a31/setup.py#L39) as a dependency for python < 3 but requests requirest  urllib3>=1.21.1,<1.24. 

Installing urllib3[secure]==1.23 after installing coveralls currently fixes. 

Steps to reproduce with a python2 interpreter.

pip install coveralls
coveralls

Trace is below:

```
(venv) vagrant@image:~$ python --version
Python 2.7.14
(venv) vagrant@image:~$ pip list
Package    Version
---------- -------
pip        18.1
setuptools 40.4.3
wheel      0.32.1
(venv) vagrant@image:~$ pip install coveralls                                                                                                                                                                                       [55/13518]
Collecting coveralls
  Downloading https://files.pythonhosted.org/packages/91/4f/f52682bfaa960445af93143df5ea0a98854f1a7829ff3e377932426bf48c/coveralls-1.5.1-py2.py3-none-any.whl
Collecting coverage>=3.6 (from coveralls)
  Downloading https://files.pythonhosted.org/packages/95/b7/9f5f35eaa6515d3d28ef8e48bb7ccf231f123fd27a07e0090580533336f9/coverage-4.5.1-cp27-cp27m-manylinux1_x86_64.whl (199kB)
    100% |████████████████████████████████| 204kB 7.5MB/s
Collecting requests>=1.0.0 (from coveralls)
  Downloading https://files.pythonhosted.org/packages/65/47/7e02164a2a3db50ed6d8a6ab1d6d60b69c4c3fdf57a284257925dfc12bda/requests-2.19.1-py2.py3-none-any.whl (91kB)
    100% |████████████████████████████████| 92kB 6.6MB/s
Collecting urllib3[secure]; python_version < "3" (from coveralls)
  Downloading https://files.pythonhosted.org/packages/8c/4b/5cbc4cb46095f369117dcb751821e1bef9dd86a07c968d8757e9204c324c/urllib3-1.24-py2.py3-none-any.whl (117kB)
    100% |████████████████████████████████| 122kB 8.9MB/s
Collecting docopt>=0.6.1 (from coveralls)
  Downloading https://files.pythonhosted.org/packages/a2/55/8f8cab2afd404cf578136ef2cc5dfb50baa1761b68c9da1fb1e4eed343c9/docopt-0.6.2.tar.gz
Collecting idna<2.8,>=2.5 (from requests>=1.0.0->coveralls)
  Downloading https://files.pythonhosted.org/packages/4b/2a/0276479a4b3caeb8a8c1af2f8e4355746a97fab05a372e4a2c6a6b876165/idna-2.7-py2.py3-none-any.whl (58kB)
    100% |████████████████████████████████| 61kB 9.1MB/s
Collecting certifi>=2017.4.17 (from requests>=1.0.0->coveralls)
  Downloading https://files.pythonhosted.org/packages/56/9d/1d02dd80bc4cd955f98980f28c5ee2200e1209292d5f9e9cc8d030d18655/certifi-2018.10.15-py2.py3-none-any.whl (146kB)
    100% |████████████████████████████████| 153kB 11.0MB/s
Collecting chardet<3.1.0,>=3.0.2 (from requests>=1.0.0->coveralls)
  Downloading https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl (133kB)
    100% |████████████████████████████████| 143kB 7.7MB/s
Collecting pyOpenSSL>=0.14; extra == "secure" (from urllib3[secure]; python_version < "3"->coveralls)
  Downloading https://files.pythonhosted.org/packages/96/af/9d29e6bd40823061aea2e0574ccb2fcf72bfd6130ce53d32773ec375458c/pyOpenSSL-18.0.0-py2.py3-none-any.whl (53kB)
    100% |████████████████████████████████| 61kB 10.6MB/s
Collecting cryptography>=1.3.4; extra == "secure" (from urllib3[secure]; python_version < "3"->coveralls)
  Downloading https://files.pythonhosted.org/packages/3a/5a/cbdcb83988aad2a0363efe1b96f2a75a197449835221db63121da1063b15/cryptography-2.3.1-cp27-cp27m-manylinux1_x86_64.whl (2.1MB)
    100% |████████████████████████████████| 2.1MB 6.6MB/s
Collecting ipaddress; extra == "secure" (from urllib3[secure]; python_version < "3"->coveralls)
  Downloading https://files.pythonhosted.org/packages/fc/d0/7fc3a811e011d4b388be48a0e381db8d990042df54aa4ef4599a31d39853/ipaddress-1.0.22-py2.py3-none-any.whl
Collecting six>=1.5.2 (from pyOpenSSL>=0.14; extra == "secure"->urllib3[secure]; python_version < "3"->coveralls)
  Downloading https://files.pythonhosted.org/packages/67/4b/141a581104b1f6397bfa78ac9d43d8ad29a7ca43ea90a2d863fe3056e86a/six-1.11.0-py2.py3-none-any.whl
Collecting asn1crypto>=0.21.0 (from cryptography>=1.3.4; extra == "secure"->urllib3[secure]; python_version < "3"->coveralls)
  Downloading https://files.pythonhosted.org/packages/ea/cd/35485615f45f30a510576f1a56d1e0a7ad7bd8ab5ed7cdc600ef7cd06222/asn1crypto-0.24.0-py2.py3-none-any.whl (101kB)
    100% |████████████████████████████████| 102kB 4.7MB/s
Collecting enum34; python_version < "3" (from cryptography>=1.3.4; extra == "secure"->urllib3[secure]; python_version < "3"->coveralls)
  Downloading https://files.pythonhosted.org/packages/c5/db/e56e6b4bbac7c4a06de1c50de6fe1ef3810018ae11732a50f15f62c7d050/enum34-1.1.6-py2-none-any.whl
Collecting cffi!=1.11.3,>=1.7 (from cryptography>=1.3.4; extra == "secure"->urllib3[secure]; python_version < "3"->coveralls)
  Downloading https://files.pythonhosted.org/packages/5d/a7/348bf05f004e7534012dc533ee29650d88fb25bf013988518e0acf6961fa/cffi-1.11.5-cp27-cp27m-manylinux1_x86_64.whl (407kB)
    100% |████████████████████████████████| 409kB 6.1MB/s
Collecting pycparser (from cffi!=1.11.3,>=1.7->cryptography>=1.3.4; extra == "secure"->urllib3[secure]; python_version < "3"->coveralls)
  Downloading https://files.pythonhosted.org/packages/68/9e/49196946aee219aead1290e00d1e7fdeab8567783e83e1b9ab5585e6206a/pycparser-2.19.tar.gz (158kB)
    100% |████████████████████████████████| 163kB 7.7MB/s
Building wheels for collected packages: docopt, pycparser
  Running setup.py bdist_wheel for docopt ... done
  Stored in directory: /home/vagrant/.cache/pip/wheels/9b/04/dd/7daf4150b6d9b12949298737de9431a324d4b797ffd63f526e
  Running setup.py bdist_wheel for pycparser ... done
  Stored in directory: /home/vagrant/.cache/pip/wheels/f2/9a/90/de94f8556265ddc9d9c8b271b0f63e57b26fb1d67a45564511
Successfully built docopt pycparser
requests 2.19.1 has requirement urllib3<1.24,>=1.21.1, but you'll have urllib3 1.24 which is incompatible.
Installing collected packages: coverage, idna, certifi, six, asn1crypto, enum34, pycparser, cffi, ipaddress, cryptography, pyOpenSSL, urllib3, chardet, requests, docopt, coveralls
Successfully installed asn1crypto-0.24.0 certifi-2018.10.15 cffi-1.11.5 chardet-3.0.4 coverage-4.5.1 coveralls-1.5.1 cryptography-2.3.1 docopt-0.6.2 enum34-1.1.6 idna-2.7 ipaddress-1.0.22 pyOpenSSL-18.0.0 pycparser-2.19 requests-2.19.1 si
x-1.11.0 urllib3-1.24
(venv) vagrant@image:~$ coveralls --debug
/home/vagrant/venv/lib/python2.7/site-packages/requests/__init__.py:91: RequestsDependencyWarning: urllib3 (1.24) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)
Traceback (most recent call last):
  File "/home/vagrant/venv/bin/coveralls", line 7, in <module>
    from coveralls.cli import main
  File "/home/vagrant/venv/lib/python2.7/site-packages/coveralls/__init__.py", line 2, in <module>
    from .api import Coveralls
  File "/home/vagrant/venv/lib/python2.7/site-packages/coveralls/api.py", line 9, in <module>
    import requests
  File "/home/vagrant/venv/lib/python2.7/site-packages/requests/__init__.py", line 112, in <module>
    from . import utils
  File "/home/vagrant/venv/lib/python2.7/site-packages/requests/utils.py", line 26, in <module>
    from ._internal_utils import to_native_string
  File "/home/vagrant/venv/lib/python2.7/site-packages/requests/_internal_utils.py", line 11, in <module>
    from .compat import is_py2, builtin_str, str
  File "/home/vagrant/venv/lib/python2.7/site-packages/requests/compat.py", line 48, in <module>
    from urllib3.packages.ordered_dict import OrderedDict
ImportError: No module named ordered_dict
```

**Comment by wwaltersp** [comment]
Working now.

**Comment by TheKevJames** [comment]
Great, thanks!
